"""Make rating, ranking, and review nullable

Revision ID: 61de613fb71d
Revises: 
Create Date: 2025-03-04 12:34:37.003207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61de613fb71d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('review',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('review',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
